# Generated by Django 5.2.14 on 2026-05-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
        ("doctors", "0002_doctorprofile_email_doctorprofile_phone_and_more"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnavailableDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=160)),
                ("is_for_all_doctors", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailable_dates",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailable_dates",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("clinic", "date", "doctor")},
            },
        ),
    ]
