# Generated by Django 5.2.14 on 2026-05-17 13:03

from django.db import migrations


def dedupe_unavailable_dates(apps, schema_editor):
    UnavailableDate = apps.get_model("scheduling", "UnavailableDate")
    seen = set()
    for item in UnavailableDate.objects.order_by("clinic_id", "date", "id"):
        key = (item.clinic_id, item.date)
        if key in seen:
            item.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0005_alter_clinicmembership_role"),
        ("scheduling", "0002_unavailabledate"),
    ]

    operations = [
        migrations.RunPython(dedupe_unavailable_dates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="unavailabledate",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="blockedtime",
            name="doctor",
        ),
        migrations.DeleteModel(
            name="DoctorWorkingHour",
        ),
        migrations.RemoveField(
            model_name="unavailabledate",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="unavailabledate",
            name="is_for_all_doctors",
        ),
        migrations.AlterUniqueTogether(
            name="unavailabledate",
            unique_together={("clinic", "date")},
        ),
    ]
