# Generated by Django 5.2.14 on 2026-05-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_remove_blockedtime_doctor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockedTime",
        ),
    ]
