# Generated by Django 5.2.14 on 2026-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                help_text="Primary email for staff booking notifications",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="reminder_hours_before",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours before appointment to send patient reminder",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="staff_notification_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated additional emails for staff notifications",
            ),
        ),
    ]
