# Generated by Django 5.2.13 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinic_notification_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="show_reason_field",
            field=models.BooleanField(default=True),
        ),
    ]
