# Generated by Django 5.2.14 on 2026-05-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_clinic_show_reason_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="notification_email",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="reminder_hours_before",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="staff_notification_emails",
        ),
    ]
