# Generated by Django 5.2.14 on 2026-05-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_remove_clinic_notification_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Clinic Admin/Owner"),
                    ("staff", "Receptionist/Staff"),
                ],
                max_length=24,
            ),
        ),
    ]
