# Generated by Django 5.2.14 on 2026-06-01 05:10

import django.core.validators
import re
from django.db import migrations, models


DEFAULT_WIDGET_ACCENT_COLOR = "#0891b2"
HEX_COLOR_RE = re.compile(r"^#[0-9A-Fa-f]{6}$")


def clean_widget_accent_colors(apps, schema_editor):
    Clinic = apps.get_model("clinics", "Clinic")
    for clinic in Clinic.objects.all().only("id", "widget_accent_color"):
        value = clinic.widget_accent_color or ""
        if len(value) > 7 or not HEX_COLOR_RE.fullmatch(value):
            clinic.widget_accent_color = DEFAULT_WIDGET_ACCENT_COLOR
            clinic.save(update_fields=["widget_accent_color"])


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0007_clinicaisettings"),
    ]

    operations = [
        migrations.RunPython(clean_widget_accent_colors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clinic",
            name="widget_accent_color",
            field=models.CharField(
                default="#0891b2",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color such as #0891b2.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
