# Generated by Django 5.2.14 on 2026-06-02 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_alter_clinic_widget_accent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='widget_accent_color',
            field=models.CharField(default='#06b6d4', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color such as #06b6d4.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
