# Generated by Django 5.2.14 on 2026-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_alter_clinic_widget_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='requires_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
