# Generated by Django 5.2.14 on 2026-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_clinic_requires_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaisettings',
            name='messenger_response_mode',
            field=models.CharField(choices=[('quick_replies', 'Quick replies'), ('ai', 'AI mode')], default='quick_replies', max_length=24),
        ),
    ]
