# Generated by Django 5.2.14 on 2026-06-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_clinicaisettings_messenger_response_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaisettings',
            name='fallback_message',
            field=models.TextField(blank=True, default='Sorry, the assistant is unavailable right now. You can still book an appointment using the booking form.'),
        ),
    ]
