# Generated by Django 5.2.14 on 2026-06-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_alter_clinicaisettings_fallback_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='show_reason_field',
        ),
    ]
