# Generated by Django 5.2.14 on 2026-06-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_alter_clinicaisettings_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaisettings',
            name='communication_tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('warm', 'Warm'), ('empathetic', 'Empathetic'), ('concise', 'Concise'), ('friendly', 'Friendly')], default='professional', max_length=24),
        ),
        migrations.AddField(
            model_name='clinicaisettings',
            name='custom_tone_instructions',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
