# Generated by Django 5.2.14 on 2026-06-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0017_alter_clinicaisettings_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('openai_compatible', 'OpenAI-compatible')], default='openai', max_length=32)),
                ('base_url', models.URLField(default='https://api.openai.com/v1', max_length=255)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('api_key', models.CharField(blank=True, default='', max_length=512)),
                ('is_enabled', models.BooleanField(default=False)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Clinic AI Provider Settings',
                'verbose_name_plural': 'Clinic AI Provider Settings',
            },
        ),
    ]
