# Generated by Django 5.2.14 on 2026-06-09 11:43

from django.db import migrations, models


def copy_existing_model_to_fallback(apps, schema_editor):
    ClinicAIProviderSettings = apps.get_model('clinics', 'ClinicAIProviderSettings')
    ClinicAIProviderSettings.objects.filter(model__gt="").update(fallback_model=models.F("model"))


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_clinicaiprovidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaiprovidersettings',
            name='fallback_model',
            field=models.CharField(default='gpt-4o-mini', max_length=120),
        ),
        migrations.RunPython(copy_existing_model_to_fallback, migrations.RunPython.noop),
    ]
