# Generated by Django 5.2.14 on 2026-06-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_clinicaiprovidersettings_fallback_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaiprovidersettings',
            name='is_enabled',
        ),
    ]
