from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.home, name="home"),
    path("calendar/", views.calendar, name="calendar"),
    path("calendar/events/", views.calendar_events, name="calendar_events"),
    path("calendar/reschedule/", views.calendar_reschedule, name="calendar_reschedule"),
    path("appointments/", views.appointments, name="appointments"),
    path("appointments/create/", views.create_appointment, name="create_appointment"),
    path("appointments/<int:pk>/", views.appointment_detail, name="appointment_detail"),
    path("appointments/<int:pk>/edit/", views.appointment_edit, name="appointment_edit"),
    path("appointments/<int:pk>/update/", views.update_appointment, name="update_appointment"),
    path("appointments/<int:pk>/cancel/", views.appointment_cancel, name="appointment_cancel"),
    path("appointments/<int:pk>/delete/", views.delete_appointment, name="delete_appointment"),
    path("appointments/<int:pk>/reschedule/", views.appointment_reschedule, name="appointment_reschedule"),
    path("appointments/<int:pk>/notes/", views.add_appointment_note, name="add_appointment_note"),
    path("appointments/<int:pk>/yakap-ledger/", views.appointment_yakap_ledger, name="appointment_yakap_ledger"),
    path("appointments/export/", views.export_csv, name="export_csv"),
    path("patients/", views.patients, name="patients"),
    path("patients/create/", views.create_patient, name="create_patient"),
    path("patients/<int:pk>/", views.patient_detail, name="patient_detail"),
    path("patients/<int:pk>/edit/", views.patient_edit, name="patient_edit"),
    path("patients/<int:pk>/delete/", views.delete_patient, name="delete_patient"),

    path("patients/duplicates/", views.find_duplicates, name="find_duplicates"),
    path("patients/merge/", views.patient_merge, name="patient_merge"),
    path("services/", views.services, name="services"),
    path("services/create/", views.create_service, name="create_service"),
    path("services/<int:pk>/edit/", views.edit_service, name="edit_service"),
    path("services/<int:pk>/toggle/", views.toggle_service, name="toggle_service"),
    path("services/<int:pk>/archive/", views.archive_service, name="archive_service"),
    path("services/<int:pk>/restore/", views.restore_service, name="restore_service"),
    path("services/<int:pk>/delete/", views.delete_service, name="delete_service"),
    path("assistant/", views.assistant_settings, name="assistant_settings"),
    path("assistant/faqs/create/", views.create_faq, name="create_faq"),
    path("assistant/faqs/<int:pk>/edit/", views.edit_faq, name="edit_faq"),
    path("assistant/faqs/<int:pk>/toggle/", views.toggle_faq, name="toggle_faq"),
    path("assistant/faqs/<int:pk>/delete/", views.delete_faq, name="delete_faq"),
    path("yakap/", views.yakap, name="yakap"),
    path("widget/embed/", views.widget_embed, name="widget_embed"),
    path("settings/", views.settings, name="settings"),
    path("settings/hours/", views.business_hours, name="business_hours"),
    path("settings/hours/save/", views.save_business_hours, name="save_business_hours"),
    path("settings/unavailable/", views.unavailable_dates, name="unavailable_dates"),
    path("settings/unavailable/create/", views.create_unavailable_date, name="create_unavailable_date"),
    path("settings/unavailable/<int:pk>/delete/", views.delete_unavailable_date, name="delete_unavailable_date"),
    path("settings/slot-preview/", views.slot_preview, name="slot_preview"),
    path("settings/messenger/", views.messenger_settings, name="messenger_settings"),
    path("settings/messenger/secret/reveal/", views.messenger_secret_reveal, name="messenger_secret_reveal"),
    path("settings/messenger/disconnect/", views.messenger_disconnect, name="messenger_disconnect"),
    path("billing/", views.billing, name="billing"),
    path("search/", views.search, name="search"),
    path("profile/", views.profile, name="profile"),
]
