# Generated by Django 5.2.14 on 2026-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="color",
            field=models.CharField(default="#0891b2", max_length=7),
        ),
        migrations.AddField(
            model_name="service",
            name="display_price",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
