# Generated by Django 5.2.14 on 2026-05-16 12:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_remove_clinic_notification_email_and_more"),
        ("doctors", "0002_doctorprofile_email_doctorprofile_phone_and_more"),
        ("services", "0002_service_color_service_display_price_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="service",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("clinic", "name"), name="unique_service_name_per_clinic"
            ),
        ),
    ]
