# Generated by Django 5.2.14 on 2026-05-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_unique_together_alter_service_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="doctors",
        ),
    ]
