# Generated by Django 5.2.14 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(default='#06b6d4', max_length=7),
        ),
    ]
