# Generated by Django 5.2.14 on 2026-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='display_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
