# Generated by Django 5.2.14 on 2026-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_display_price_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='simultaneous_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
