# Generated by Django 5.2.14 on 2026-06-09 14:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_appointment_messenger_psid_and_more'),
        ('clinics', '0017_alter_clinicaisettings_instructions'),
        ('patients', '0002_patient_date_of_birth'),
        ('services', '0005_alter_service_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentYakapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested', models.BooleanField(default=False)),
                ('coverage_status', models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('unverified', 'Unverified'), ('verified', 'Verified'), ('not_eligible', 'Not eligible'), ('exceeded', 'Exceeded'), ('not_applicable', 'Not applicable')], default='not_requested', max_length=32)),
                ('category_name', models.CharField(blank=True, default='', max_length=120)),
                ('service_rule_status', models.CharField(blank=True, default='', max_length=32)),
                ('estimated_remaining_at_booking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_snapshot', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_appointment_snapshots', to='clinics.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicYakapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('public_promo_headline', models.CharField(default='Use your PhilHealth YAKAP benefits', max_length=160)),
                ('public_promo_body', models.TextField(default='Book eligible YAKAP primary care services, subject to PhilHealth and clinic verification.')),
                ('public_disclaimer', models.TextField(default='YAKAP eligibility and remaining coverage must be verified by clinic staff.')),
                ('internal_disclaimer', models.TextField(default='All KliniAssist YAKAP balances are estimates, not official PhilHealth balances.')),
                ('verification_instructions', models.TextField(blank=True, default="Verify eligibility through the clinic's PhilHealth workflow before service.")),
                ('default_annual_credit', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reset_month', models.PositiveSmallIntegerField(default=1)),
                ('reset_day', models.PositiveSmallIntegerField(default=1)),
                ('hard_block_exceeded', models.BooleanField(default=False)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_settings', to='clinics.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientYakapProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_asked', 'Not asked'), ('interested', 'Interested'), ('registered_elsewhere', 'Registered elsewhere'), ('registered_to_this_clinic', 'Registered to this clinic'), ('fpe_completed', 'FPE completed'), ('yes_signed', 'YES signed'), ('active', 'Active'), ('inactive', 'Inactive')], default='interested', max_length=32)),
                ('annual_limit_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_patient_profiles', to='clinics.clinic')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_profile', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YakapCoverageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category_type', models.CharField(choices=[('primary_care', 'Primary Care'), ('laboratory', 'Laboratory'), ('medicines', 'Medicines'), ('cancer_screening', 'Cancer Screening'), ('other', 'Other')], default='other', max_length=32)),
                ('annual_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_categories', to='clinics.clinic')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceYakapRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_status', models.CharField(choices=[('covered', 'Covered'), ('possibly_covered', 'Possibly covered'), ('not_covered', 'Not covered'), ('cash_only', 'Cash only'), ('requires_verification', 'Requires verification')], default='requires_verification', max_length=32)),
                ('estimated_covered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('requires_verification', models.BooleanField(default=True)),
                ('public_badge_label', models.CharField(blank=True, default='', max_length=80)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_service_rules', to='clinics.clinic')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_rule', to='services.service')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_rules', to='yakap.yakapcoveragecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YakapLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('service_usage', 'Service usage'), ('medicine_usage', 'Medicine usage'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=32)),
                ('note', models.TextField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yakap_ledger_entries', to='appointments.appointment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='yakap.yakapcoveragecategory')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_ledger_entries', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_ledger_entries', to='patients.patient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='yakap.patientyakapprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yakap_ledger_entries', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='yakapcoveragecategory',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_yakap_category_per_clinic'),
        ),
    ]
