# Generated by Django 5.2.14 on 2026-06-10 13:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0019_clinicaiprovidersettings_fallback_model'),
        ('patients', '0002_patient_date_of_birth'),
        ('yakap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentyakapsnapshot',
            name='estimated_covered_amount_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='appointmentyakapsnapshot',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentyakapsnapshot',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentyakapsnapshot',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_yakap_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicyakapsettings',
            name='default_non_medicine_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='clinicyakapsettings',
            name='low_balance_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='clinicyakapsettings',
            name='medicine_annual_limit_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='clinicyakapsettings',
            name='program_label',
            field=models.CharField(default='YAKAP', max_length=40),
        ),
        migrations.AddField(
            model_name='clinicyakapsettings',
            name='verification_stale_after_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='patientyakapprofile',
            name='consent_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientyakapprofile',
            name='last_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_yakap_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientyakapprofile',
            name='registered_clinic_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='patientyakapprofile',
            name='verification_method',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='patientyakapprofile',
            name='verification_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='yakapledgerentry',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='yakapledgerentry',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yakapledgerentry',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='yakap.yakapledgerentry'),
        ),
        migrations.AddField(
            model_name='yakapledgerentry',
            name='source',
            field=models.CharField(default='manual_dashboard', max_length=40),
        ),
        migrations.AddField(
            model_name='yakapledgerentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yakapledgerentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_yakap_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentyakapsnapshot',
            name='coverage_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('unverified', 'Unverified'), ('verified', 'Verified'), ('not_eligible', 'Not eligible'), ('exceeded', 'Exceeded'), ('not_applicable', 'Not applicable'), ('needs_verification', 'Needs verification'), ('verified_for_visit', 'Verified for visit'), ('exceeded_estimate', 'Exceeded estimate'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='not_requested', max_length=32),
        ),
        migrations.AlterField(
            model_name='patientyakapprofile',
            name='status',
            field=models.CharField(choices=[('not_asked', 'Not asked'), ('interested', 'Interested'), ('pending_verification', 'Pending verification'), ('registered_elsewhere', 'Registered elsewhere'), ('registered_to_this_clinic', 'Registered to this clinic'), ('fpe_completed', 'FPE completed'), ('yes_signed', 'YES signed'), ('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='interested', max_length=32),
        ),
        migrations.AlterField(
            model_name='yakapledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('service_usage', 'Service usage'), ('medicine_usage', 'Medicine usage'), ('laboratory_usage', 'Laboratory usage'), ('screening_usage', 'Screening usage'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=32),
        ),
        migrations.CreateModel(
            name='YakapAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('settings_changed', 'Settings changed'), ('profile_status_changed', 'Profile status changed'), ('appointment_status_changed', 'Appointment status changed'), ('ledger_posted', 'Ledger posted'), ('ledger_reversed', 'Ledger reversed'), ('export_created', 'Export created')], max_length=40)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yakap_audit_events', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_audit_events', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YakapCreditLinePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('limit_snapshot', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('superseded', 'Superseded')], default='open', max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_line_periods', to='yakap.yakapcoveragecategory')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_credit_line_periods', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yakap_credit_line_periods', to='patients.patient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_line_periods', to='yakap.patientyakapprofile')),
            ],
            options={
                'ordering': ['-period_start', '-period_end', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'category', 'period_start', 'period_end'), name='unique_yakap_credit_period_per_profile_category')],
            },
        ),
    ]
