# Generated by Django 5.2.13 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_cancellation_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="cancellation_reason",
        ),
        migrations.AddField(
            model_name="appointment",
            name="reference_code",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
