# Generated by Django 5.2.14 on 2026-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_remove_appointment_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
    ]
