# Generated by Django 5.2.14 on 2026-05-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_cancellation_reason"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_doctor__60bd67_idx",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
    ]
