# Generated by Django 5.2.14 on 2026-06-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_appointment_doctor__60bd67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='messenger_psid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='messenger_reminder_1h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='messenger_reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
