# Generated by Django 5.2.14 on 2026-06-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_messenger_psid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct booking'), ('embed', 'Embed'), ('chat_widget', 'Chat widget'), ('staff', 'Staff'), ('walk_in', 'Walk-in'), ('phone', 'Phone'), ('messenger', 'Messenger'), ('voice_widget', 'Voice widget')], default='direct', max_length=32),
        ),
    ]
