# Generated by Django 5.2.14 on 2026-06-19 13:18

import django.db.models.deletion
import django.utils.timezone
import voice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0020_remove_clinicaiprovidersettings_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('display_name', models.CharField(default='Voice Assistant', max_length=80)),
                ('voice_label', models.CharField(choices=[('professional', 'Professional'), ('warm', 'Warm'), ('concise', 'Concise')], default='professional', max_length=32)),
                ('welcome_message', models.TextField(default='Hi, I can help with clinic questions and appointments. How can I help?')),
                ('provider', models.CharField(choices=[('browser', 'Browser'), ('vapi', 'Vapi'), ('retell', 'Retell'), ('twilio_openai', 'Twilio OpenAI'), ('custom', 'Custom')], default='browser', max_length=32)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('provider_secret_ref', models.CharField(blank=True, default='', max_length=255)),
                ('is_test_mode_enabled', models.BooleanField(default=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_agent_settings', to='clinics.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_session_id', models.CharField(default=voice.models._public_session_id, max_length=64, unique=True)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=80)),
                ('provider', models.CharField(default='browser', max_length=32)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('source', models.CharField(choices=[('widget', 'Widget'), ('dashboard_test', 'Dashboard test')], default='widget', max_length=32)),
                ('is_test', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTranscriptTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('partial', 'Partial'), ('final', 'Final'), ('failed', 'Failed')], default='final', max_length=16)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=120)),
                ('sequence', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_turns', to='voice.voicesession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['clinic', 'status', 'last_activity_at'], name='voice_voice_clinic__557efe_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicetranscriptturn',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_voice_transcript_sequence'),
        ),
        migrations.AddConstraint(
            model_name='voicetranscriptturn',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('session', 'provider_event_id'), name='unique_voice_transcript_provider_event'),
        ),
    ]
