# Generated by Django 5.2.14 on 2026-06-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceagentsettings',
            name='emotion_mode',
            field=models.CharField(choices=[('adaptive', 'Adaptive'), ('fixed', 'Fixed'), ('off', 'Off')], default='adaptive', max_length=24),
        ),
        migrations.AddField(
            model_name='voiceagentsettings',
            name='emotion_intensity',
            field=models.CharField(choices=[('subtle', 'Subtle'), ('balanced', 'Balanced'), ('expressive', 'Expressive')], default='balanced', max_length=24),
        ),
        migrations.AddField(
            model_name='voiceagentsettings',
            name='fixed_emotion',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('warm', 'Warm'), ('reassuring', 'Reassuring'), ('concise', 'Concise'), ('celebratory', 'Celebratory')], default='warm', max_length=24),
        ),
    ]
