# Generated by Django 5.2.14 on 2026-05-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0006_remove_doctor_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessengerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_id", models.CharField(max_length=64)),
                ("page_access_token", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messenger_connection",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessengerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("psid", models.CharField(db_index=True, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("select_service", "Select Service"),
                            ("select_date", "Select Date"),
                            ("select_time", "Select Time"),
                            ("collect_info", "Collect Info"),
                            ("confirm", "Confirm"),
                            ("booked", "Booked"),
                            ("faq", "FAQ"),
                        ],
                        default="greeting",
                        max_length=32,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="messenger.messengerconnection",
                    ),
                ),
            ],
            options={
                "unique_together": {("connection", "psid")},
            },
        ),
    ]
