# Generated by Django 5.2.13 on 2026-05-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="messengersession",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="messengersession",
            constraint=models.UniqueConstraint(
                fields=("connection", "psid"), name="unique_messenger_session_psid"
            ),
        ),
    ]
