# Generated by Django 5.2.14 on 2026-05-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_alter_messengersession_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessengerPlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "app_secret",
                    models.CharField(blank=True, default="", max_length=256),
                ),
            ],
            options={
                "verbose_name": "Messenger Platform Config",
                "verbose_name_plural": "Messenger Platform Config",
            },
        ),
    ]
