# Generated by Django 5.2.14 on 2026-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_messengerplatformconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessengerPlatformConfig",
        ),
        migrations.AddField(
            model_name="messengerconnection",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shared secret for n8n webhook authentication",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="messengerconnection",
            name="page_access_token",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="messengerconnection",
            name="page_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
