# Generated by Django 5.2.14 on 2026-05-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_delete_messengerplatformconfig_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messengerconnection",
            name="webhook_secret",
        ),
    ]
