# Generated by Django 5.2.14 on 2026-05-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_remove_messengerconnection_webhook_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessengerAISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_ai_enabled", models.BooleanField(default=True)),
                ("instructions", models.TextField(blank=True, default="")),
                ("fallback_message", models.TextField(blank=True, default="")),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="messenger.messengerconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messenger AI Settings",
                "verbose_name_plural": "Messenger AI Settings",
            },
        ),
    ]
