# Generated by Django 5.2.14 on 2026-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0007_clinicaisettings"),
        ("messenger", "0007_alter_messengeraisettings_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="messengerconnection",
            name="app_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="messengerconnection",
            name="app_secret",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddConstraint(
            model_name="messengerconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page_id", ""), _negated=True),
                fields=("page_id",),
                name="unique_messenger_connection_page_id",
            ),
        ),
    ]
