# Generated by Django 5.2.14 on 2026-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_messengerconnection_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconnection',
            name='page_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
