# Generated by Django 5.2.14 on 2026-06-06 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_alter_messengeraisettings_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psid', models.CharField(db_index=True, max_length=64)),
                ('message_id', models.CharField(max_length=128)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_messages', to='messenger.messengerconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'psid', 'message_id'), name='unique_messenger_processed_message')],
            },
        ),
    ]
