# Generated by Django 5.2.14 on 2026-06-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_messengerprocessedmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psid', models.CharField(db_index=True, max_length=64)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('completed_sequence', models.PositiveIntegerField(default=0)),
                ('active_turn_token', models.CharField(blank=True, default='', max_length=64)),
                ('active_input_sequence', models.PositiveIntegerField(default=0)),
                ('history', models.JSONField(blank=True, default=list)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='messenger.messengerconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'psid'), name='unique_messenger_ai_conversation_psid')],
            },
        ),
        migrations.CreateModel(
            name='MessengerAITurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('input_sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('completed', 'Completed'), ('stale', 'Stale')], default='active', max_length=24)),
                ('reply_text', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_turns', to='messenger.messengerconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(blank=True, default='', max_length=128)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('postback', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='messenger.messengerconversation')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [
                    models.UniqueConstraint(fields=('conversation', 'sequence'), name='unique_messenger_inbound_sequence'),
                    models.UniqueConstraint(condition=~models.Q(('message_id', '')), fields=('conversation', 'message_id'), name='unique_messenger_inbound_message_id'),
                ],
            },
        ),
    ]
