# Generated by Django 5.2.14 on 2026-06-12 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_alter_messengeraisettings_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeraiturn',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('sending', 'Sending'), ('superseded', 'Superseded'), ('completed', 'Completed'), ('stale', 'Stale')], default='active', max_length=24),
        ),
        migrations.CreateModel(
            name='MessengerOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_index', models.PositiveIntegerField()),
                ('body_hash', models.CharField(max_length=64)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Delivery Unknown')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='messenger.messengeraiturn')),
            ],
            options={
                'ordering': ['body_index'],
                'constraints': [models.UniqueConstraint(fields=('turn', 'body_index'), name='unique_messenger_outbound_turn_body')],
            },
        ),
    ]
