# Generated by Django 5.2.13 on 2026-05-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=40)),
                ("normalized_phone", models.CharField(db_index=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "normalized_phone"],
                        name="patients_pa_clinic__22d802_idx",
                    )
                ],
            },
        ),
    ]
