# Generated by Django 5.2.14 on 2026-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="doctor-photos/"),
        ),
    ]
