# Generated by Django 5.2.14 on 2026-05-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0005_remove_appointment_appointment_doctor__60bd67_idx_and_more",
        ),
        ("doctors", "0002_doctorprofile_email_doctorprofile_phone_and_more"),
        ("scheduling", "0003_remove_blockedtime_doctor_and_more"),
        ("services", "0004_remove_service_doctors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorProfile",
        ),
    ]
